# Generated by Django 3.2.12 on 2022-04-23 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('configKeyID', models.AutoField(primary_key=True, serialize=False)),
                ('configName', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('projectID', models.AutoField(primary_key=True, serialize=False)),
                ('plant', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=200)),
                ('cameraIP', models.CharField(max_length=200)),
                ('cameraType', models.CharField(max_length=200)),
                ('userName', models.CharField(max_length=200)),
                ('userPassword', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ConfigValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('configValue', models.CharField(max_length=200, null=True)),
                ('configKeyID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='SafetyZone.config')),
                ('projectID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='SafetyZone.project')),
            ],
        ),
    ]
