# Generated by Django 3.2.12 on 2022-04-22 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SafetyZone', '0002_auto_20220209_0938'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigKeyValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('configValue', models.CharField(max_length=200, null=True)),
                ('configKeyID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='SafetyZone.config')),
                ('projectID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='SafetyZone.project')),
            ],
        ),
        migrations.DeleteModel(
            name='ProjectConfig',
        ),
    ]
