# Generated by Django 3.2.12 on 2022-04-22 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SafetyZone', '0003_auto_20220422_0234'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConfigKeyValues',
            new_name='ConfigValue',
        ),
        migrations.RenameField(
            model_name='config',
            old_name='configKey',
            new_name='configName',
        ),
    ]
